FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    cmake \
    git \
    qt6-base-dev \
    qt6-tools-dev \
    qt6-tools-dev-tools \
    qt6-base-dev-tools \
    qt6-declarative-dev \
    qt6-svg-dev \
    qt6-charts-dev \
    qt6-multimedia-dev \
    libsqlite3-dev \
    qt6-l10n-tools \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD [ "bash" ]
